### ISSUE TITLE
This service doesn't seem to get the combo-lock fix about "MemoryTempfile"

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-audio#14]
```
2023-05-27 18:32:48.105 - audio - ovos_utils.file_utils:get_cache_directory:61 - ERROR - 'MemoryTempfile' object has no attribute 'tempdir'
Traceback (most recent call last):
  File "/Users/goldyfruit/Virtualenvs/ovos/lib/python3.11/site-packages/ovos_utils/file_utils.py", line 57, in get_cache_directory
    path = join(MemoryTempfile(fallback=True).gettempdir(), folder)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/goldyfruit/Virtualenvs/ovos/lib/python3.11/site-packages/memory_tempfile/memory_tempfile.py", line 80, in gettempdir
    return self.tempdir
           ^^^^^^^^^^^^
AttributeError: 'MemoryTempfile' object has no attribute 'tempdir'
2023-05-27 18:32:48.111 - audio - ovos_utils.file_utils:resolve_resource_file:145 - WARNING - Expected a dict config and got None. This configfallback behavior will be deprecated in a future release
2023-05-27 18:32:48.179 - audio - mycroft:<module>:37 - WARNING - mycroft has been deprecated! please start importing from ovos_core and companion packages
mycroft module remains available for backwards compatibility and will be removed in version 0.2.0
2023-05-27 18:32:48.231 - audio - ovos_utils.file_utils:get_cache_directory:61 - ERROR - 'MemoryTempfile' object has no attribute 'tempdir'
Traceback (most recent call last):
  File "/Users/goldyfruit/Virtualenvs/ovos/lib/python3.11/site-packages/ovos_utils/file_utils.py", line 57, in get_cache_directory
    path = join(MemoryTempfile(fallback=True).gettempdir(), folder)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/goldyfruit/Virtualenvs/ovos/lib/python3.11/site-packages/memory_tempfile/memory_tempfile.py", line 80, in gettempdir
    return self.tempdir
           ^^^^^^^^^^^^
AttributeError: 'MemoryTempfile' object has no attribute 'tempdir'
```

**Comment by goldyfruit** [comment]
I think its related to the `requirements.txt`, more strict than for `ovos-dinkum-listener` for example.

**Comment by goldyfruit** [comment]
Still facing this issue even with the latest version of ` ovos-utils`.

**Comment by NeonDaniel** [comment]
Since this package doesn't directly implement memory_tempfile I assume the linked issue in ovos-utils fixed this
