### ISSUE TITLE
threads can only be started once

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-audio#50]
```
2024-01-20 16:48:46.792 - audio - ovos_plugin_manager.tts:create:209 - INFO - Loaded plugin amazon
2024-01-20 16:48:46.794 - audio - ovos_config.config:_on_file_change:321 - ERROR - Error in config update callback handler
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_config/config.py", line 319, in _on_file_change
    handler()
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_audio/service.py", line 314, in _maybe_reload_tts
    self.tts.init(self.bus, self.playback_thread)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/templates/tts.py", line 325, in init
    self._init_playback(playback)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/templates/tts.py", line 336, in _init_playback
    TTS.playback.start()
  File "/usr/lib/python3.11/threading.py", line 952, in start
    raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once
```

**Comment by goldyfruit** [comment]
@joergz got the same as well this morning.

```
2024-01-26 15:37:25.688 - audio - ovos_config.config:_on_file_change:315 - INFO - /home/pi/.config/mycroft/mycroft.conf changed on disk
2024-01-26 15:37:25.692 - audio - ovos_audio.service:_maybe_reload_tts:312 - INFO - (re)loading TTS engine
2024-01-26 15:37:25.742 - audio - ovos_plugin_manager.tts:create:205 - INFO - Found plugin ovos-tts-plugin-server
2024-01-26 15:37:25.877 - audio - ovos_plugin_manager.tts:create:209 - INFO - Loaded plugin ovos-tts-plugin-server
2024-01-26 15:37:25.879 - audio - ovos_config.config:_on_file_change:321 - ERROR - Error in config update callback handler
Traceback (most recent call last):
  File "/home/pi/.venvs/ovos/lib/python3.11/site-packages/ovos_config/config.py", line 319, in _on_file_change
    handler()
  File "/home/pi/.venvs/ovos/lib/python3.11/site-packages/ovos_audio/service.py", line 314, in _maybe_reload_tts
    self.tts.init(self.bus, self.playback_thread)
  File "/home/pi/.venvs/ovos/lib/python3.11/site-packages/ovos_plugin_manager/templates/tts.py", line 326, in init
    self._init_playback(playback)
  File "/home/pi/.venvs/ovos/lib/python3.11/site-packages/ovos_plugin_manager/templates/tts.py", line 337, in _init_playback
    TTS.playback.start()
  File "/usr/lib/python3.11/threading.py", line 952, in start
    raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once
```
