### ISSUE TITLE
Session ID error

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-audio#8]
Sometime the service returns this in the log.
```
2023-04-11 19:12:03.643 - audio - ovos_bus_client.session:reset_default_session:171 - INFO - New Default Session Start: 20f5500b-e903-4261-a9b2-03be844c4547
2023-04-11 19:12:03.656 - audio - ovos_workshop.skills.base:_on_event_error:1324 - ERROR - '0b05d7b4-d03a-4b1a-86d0-c58f53ba1c56'
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_utils/messagebus.py", line 515, in wrapper
    handler(message)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/base.py", line 820, in _handle_converse_ack
    self.bus.emit(message.reply(
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_bus_client/client/client.py", line 145, in emit
    sess = SessionManager.get(message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_bus_client/session.py", line 188, in get
    SessionManager.sessions.pop(SessionManager.default_session.session_id)
KeyError: '0b05d7b4-d03a-4b1a-86d0-c58f53ba1c56'
2023-04-11 19:12:03.724 - audio - ovos_audio.service:execute_tts:311 - INFO - Speak: seven twelve
2023-04-11 19:12:04.385 - audio - ovos_plugin_manager.templates.tts:_execute:761 - DEBUG - no mouth movements available! unknown visemes for seven twelve
2023-04-11 19:12:11.010 - audio - ovos_audio.audio:_restore_volume_after_record:281 - DEBUG - No audio service to restore volume of
2023-04-11 19:12:13.542 - audio - ovos_audio.service:execute_tts:311 - INFO - Speak: Right now, it's 16 degrees.
2023-04-11 19:12:14.476 - audio - ovos_plugin_manager.templates.tts:_execute:761 - DEBUG - no mouth movements available! unknown visemes for Right now, it's 16 degrees.
2023-04-11 19:58:28.279 - audio - ovos_audio.audio:_restore_volume_after_record:281 - DEBUG - No audio service to restore volume of
2023-04-11 19:58:30.245 - audio - ovos_bus_client.session:reset_default_session:171 - INFO - New Default Session Start: 00f75a3a-d572-4b10-976f-0b55a38eed07
2023-04-11 19:58:30.253 - audio - ovos_workshop.skills.base:_on_event_error:1324 - ERROR - '20f5500b-e903-4261-a9b2-03be844c4547'
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_utils/messagebus.py", line 515, in wrapper
    handler(message)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/base.py", line 820, in _handle_converse_ack
    self.bus.emit(message.reply(
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_bus_client/client/client.py", line 145, in emit
    sess = SessionManager.get(message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_bus_client/session.py", line 188, in get
    SessionManager.sessions.pop(SessionManager.default_session.session_id)
KeyError: '20f5500b-e903-4261-a9b2-03be844c4547'
```

**Comment by goldyfruit** [comment]
This adds some delay to the response.

```
2023-04-11 20:57:57.407 - audio - ovos_audio.audio:_restore_volume_after_record:281 - DEBUG - No audio service to restore volume of
2023-04-11 20:57:59.321 - audio - ovos_bus_client.session:reset_default_session:171 - INFO - New Default Session Start: 500ba30e-be8f-49c5-929f-360d894174ba
2023-04-11 20:57:59.325 - audio - ovos_workshop.skills.base:_on_event_error:1324 - ERROR - 'f915f0cc-3085-4a72-b24b-cfc2341caa37'
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_utils/messagebus.py", line 515, in wrapper
    handler(message)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/base.py", line 820, in _handle_converse_ack
    self.bus.emit(message.reply(
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_bus_client/client/client.py", line 145, in emit
    sess = SessionManager.get(message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_bus_client/session.py", line 188, in get
    SessionManager.sessions.pop(SessionManager.default_session.session_id)
KeyError: 'f915f0cc-3085-4a72-b24b-cfc2341caa37'
2023-04-11 20:58:01.472 - audio - ovos_audio.service:execute_tts:311 - INFO - Speak: It is eight fifty eight
2023-04-11 20:58:01.699 - audio - neon_tts_plugin_polly:_get_default_voice:120 - DEBUG - get cached voice=None
2023-04-11 20:58:01.703 - audio - neon_tts_plugin_polly:_get_default_voice:139 - DEBUG - Get Voice time=0.0025849342346191406
2023-04-11 20:58:01.705 - audio - neon_tts_plugin_polly:get_tts:82 - DEBUG - <speak>It is eight fifty eight</speak>
2023-04-11 20:58:01.972 - audio - neon_tts_plugin_polly:get_tts:93 - DEBUG - Polly time=0.26458311080932617
2023-04-11 20:58:01.980 - audio - neon_tts_plugin_polly:get_tts:100 - DEBUG - File access time=0.005814313888549805
2023-04-11 20:58:01.982 - audio - ovos_plugin_manager.templates.tts:_execute:761 - DEBUG - no mouth movements available! unknown visemes for It is eight fifty eight
```
