### ISSUE TITLE
 IndexError: list index out of range

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-audio#82]
When trying to play a song from Spotify I got this error in the audio log.
```
Jul 30 13:32:26 mark2 ovos-audio[8513]: 2024-07-30 13:32:26.570 - audio - ovos_audio.audio:_play:482 - ERROR - list index out of range
Jul 30 13:32:26 mark2 ovos-audio[8513]: Traceback (most recent call last):
Jul 30 13:32:26 mark2 ovos-audio[8513]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_audio/audio.py", line 479, in _play
Jul 30 13:32:26 mark2 ovos-audio[8513]:     self.play(tracks, prefered_service, repeat)
Jul 30 13:32:26 mark2 ovos-audio[8513]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_audio/audio.py", line 398, in play
Jul 30 13:32:26 mark2 ovos-audio[8513]:     if isinstance(tracks[0], str):
Jul 30 13:32:26 mark2 ovos-audio[8513]:                   ~~~~~~^^^
Jul 30 13:32:26 mark2 ovos-audio[8513]: IndexError: list index out of range
```

**Comment by goldyfruit** [comment]
```
Jul 30 13:43:13 mark2 ovos-core[8514]: 2024-07-30 13:43:13.601 - skills - ovos_core.transformers:transform:64 - DEBUG - ovos-utterance-cancel: {}
Jul 30 13:43:13 mark2 ovos-core[8514]: 2024-07-30 13:43:13.604 - skills - ovos_core.transformers:transform:64 - DEBUG - ovos-utterance-normalizer: {'client_name': 'mycroft_cli', 'source': 'debug_cli', 'destination': ['skills'], 'lang': 'en-us'}
Jul 30 13:43:13 mark2 ovos-core[8514]: 2024-07-30 13:43:13.606 - skills - ovos_core.transformers:transform:64 - DEBUG - ovos-utterance-corrections: {'client_name': 'mycroft_cli', 'source': 'debug_cli', 'destination': ['skills'], 'lang': 'en-us'}
Jul 30 13:43:13 mark2 ovos-core[8514]: 2024-07-30 13:43:13.616 - skills - ovos_core.intent_services:get_pipeline:241 - DEBUG - Session pipeline: ['stop_high', 'converse', 'ocp_high', 'padatious_high', 'adapt_high', 'ocp_medium', 'fallback_high', 'stop_medium', 'adapt_medium', 'padatious_medium', 'adapt_low', 'common_qa', 'fallback_medium', 'fallback_low']
Jul 30 13:43:13 mark2 ovos-core[8514]: 2024-07-30 13:43:13.618 - skills - ovos_core.intent_services:handle_utterance:382 - DEBUG - no match from <bound method StopService.match_stop_high of <ovos_core.intent_services.stop_service.StopService object at 0x7f6c2a96d0>>
Jul 30 13:43:13 mark2 ovos-core[8514]: 2024-07-30 13:43:13.625 - skills - ovos_core.intent_services:handle_utterance:382 - DEBUG - no match from <bound method ConverseService.converse_with_skills of <ovos_core.intent_services.converse_service.ConverseService object at 0x7f6cd01490>>
Jul 30 13:43:14 mark2 ovos-core[8514]: 2024-07-30 13:43:14.127 - skills - padacioso:calc_intent:255 - DEBUG - {'entities': {'query': 'wutang from spotify'}, 'conf': 0.96, 'name': 'play'}
Jul 30 13:43:14 mark2 ovos-core[8514]: 2024-07-30 13:43:14.129 - skills - ovos_core.intent_services.ocp_service:match_high:366 - INFO - OCP exact match: {'entities': {'query': 'wutang from spotify'}, 'conf': 0.96, 'name': 'play'}
Jul 30 13:43:14 mark2 ovos-core[8514]: 2024-07-30 13:43:14.141 - skills - ovos_core.intent_services.ocp_service:_process_play_query:482 - INFO - OCP specific skill names matched: ['ovos-skill-spotify.openvoiceos']
Jul 30 13:43:14 mark2 ovos-core[8514]: 2024-07-30 13:43:14.144 - skills - ovos_core.intent_services:handle_utterance:370 - INFO - ocp_high match: IntentMatch(intent_service='OCP_intents', intent_type='ocp:play', intent_data={'media_type': <MediaType.GENERIC: 0>, 'query': 'wutang from spotify', 'entities': {'music_streaming_service': 'spotify'}, 'skills': ['ovos-skill-spotify.openvoiceos'], 'conf': 0.96, 'media_conf': 0.0, 'lang': 'en-us'}, skill_id='ovos.common_play', utterance='wutang from spotify')
Jul 30 13:43:14 mark2 ovos-core[8514]: 2024-07-30 13:43:14.148 - skills - ovos_core.intent_services:handle_utterance:388 - DEBUG - intent matching took: 0.5323035717010498
Jul 30 13:43:14 mark2 ovos-core[8514]: 2024-07-30 13:43:14.235 - skills - ovos_bus_client.client.client:on_default_session_update:166 - DEBUG - synced default_session
Jul 30 13:43:14 mark2 ovos-core[8514]: 2024-07-30 13:43:14.269 - skills - ovos_bus_client.apis.ocp:__init__:509 - DEBUG - Created GENERIC query: wutang from spotify
Jul 30 13:43:14 mark2 ovos-core[8514]: 2024-07-30 13:43:14.421 - skills - ovos_core.intent_services.ocp_service:_execute_query:941 - DEBUG - Searching OCP Skill: ovos-skill-spotify.openvoiceos
Jul 30 13:43:14 mark2 ovos-core[8514]: 2024-07-30 13:43:14.424 - skills - ovos_bus_client.apis.ocp:register_events:569 - DEBUG - Registering Search Bus Events
Jul 30 13:43:14 mark2 ovos-core[8514]: 2024-07-30 13:43:14.454 - skills - ovos_bus_client.apis.ocp:handle_skill_search_start:582 - DEBUG - ovos-skill-spotify.openvoiceos is searching
Jul 30 13:43:15 mark2 ovos-core[8514]: 2024-07-30 13:43:15.502 - skills - ovos_bus_client.apis.ocp:handle_skill_response:616 - DEBUG - got 1 results from ovos-skill-spotify.openvoiceos
Jul 30 13:43:15 mark2 ovos-core[8514]: 2024-07-30 13:43:15.742 - skills - ovos_bus_client.apis.ocp:handle_skill_response:616 - DEBUG - got 1 results from ovos-skill-spotify.openvoiceos
Jul 30 13:43:16 mark2 ovos-core[8514]: 2024-07-30 13:43:16.006 - skills - ovos_bus_client.apis.ocp:handle_skill_response:616 - DEBUG - got 1 results from ovos-skill-spotify.openvoiceos
Jul 30 13:43:16 mark2 ovos-core[8514]: 2024-07-30 13:43:16.035 - skills - ovos_config.config:_on_file_change:312 - DEBUG - Ignoring non-config file change: /home/goldyfruit/.config/mycroft/mycroft_cli.conf
Jul 30 13:43:16 mark2 ovos-core[8514]: 2024-07-30 13:43:16.312 - skills - ovos_bus_client.apis.ocp:handle_skill_response:616 - DEBUG - got 1 results from ovos-skill-spotify.openvoiceos
Jul 30 13:43:16 mark2 ovos-core[8514]: 2024-07-30 13:43:16.630 - skills - ovos_bus_client.apis.ocp:handle_skill_response:616 - DEBUG - got 1 results from ovos-skill-spotify.openvoiceos
Jul 30 13:43:16 mark2 ovos-core[8514]: 2024-07-30 13:43:16.914 - skills - ovos_bus_client.apis.ocp:handle_skill_response:616 - DEBUG - got 1 results from ovos-skill-spotify.openvoiceos
Jul 30 13:43:17 mark2 ovos-core[8514]: 2024-07-30 13:43:17.191 - skills - ovos_bus_client.apis.ocp:handle_skill_response:616 - DEBUG - got 1 results from ovos-skill-spotify.openvoiceos
Jul 30 13:43:17 mark2 ovos-core[8514]: 2024-07-30 13:43:17.466 - skills - ovos_bus_client.apis.ocp:handle_skill_response:616 - DEBUG - got 1 results from ovos-skill-spotify.openvoiceos
Jul 30 13:43:17 mark2 ovos-core[8514]: 2024-07-30 13:43:17.676 - skills - ovos_bus_client.apis.ocp:handle_skill_response:616 - DEBUG - got 1 results from ovos-skill-spotify.openvoiceos
Jul 30 13:43:18 mark2 ovos-core[8514]: 2024-07-30 13:43:18.019 - skills - ovos_bus_client.apis.ocp:handle_skill_response:616 - DEBUG - got 1 results from ovos-skill-spotify.openvoiceos
Jul 30 13:43:18 mark2 ovos-core[8514]: 2024-07-30 13:43:18.750 - skills - ovos_skill_spotify.spotify:query_album:212 - INFO - ('wutang from ', 'enter the wu-tang (36 chambers) [expanded edition]', 0.18000000000000005)
Jul 30 13:43:18 mark2 ovos-core[8514]: 2024-07-30 13:43:18.984 - skills - ovos_bus_client.apis.ocp:handle_skill_response:616 - DEBUG - got 1 results from ovos-skill-spotify.openvoiceos
Jul 30 13:43:19 mark2 ovos-core[8514]: 2024-07-30 13:43:19.256 - skills - ovos_bus_client.apis.ocp:handle_skill_response:616 - DEBUG - got 1 results from ovos-skill-spotify.openvoiceos
Jul 30 13:43:19 mark2 ovos-core[8514]: 2024-07-30 13:43:19.530 - skills - ovos_bus_client.apis.ocp:handle_skill_response:616 - DEBUG - got 1 results from ovos-skill-spotify.openvoiceos
Jul 30 13:43:19 mark2 ovos-core[8514]: 2024-07-30 13:43:19.533 - skills - ovos_bus_client.apis.ocp:handle_skill_response:626 - DEBUG - common play query timeout, parsing results
Jul 30 13:43:19 mark2 ovos-core[8514]: 2024-07-30 13:43:19.540 - skills - ovos_bus_client.apis.ocp:remove_events:575 - DEBUG - Removing Search Bus Events
Jul 30 13:43:19 mark2 ovos-core[8514]: 2024-07-30 13:43:19.541 - skills - ovos_core.intent_services.ocp_service:_execute_query:972 - DEBUG - Returning 13 search results
Jul 30 13:43:19 mark2 ovos-core[8514]: 2024-07-30 13:43:19.782 - skills - ovos_core.intent_services.ocp_service:_search:916 - DEBUG - Got 13 usable results from ['ovos-skill-spotify.openvoiceos']
Jul 30 13:43:19 mark2 ovos-core[8514]: 2024-07-30 13:43:19.784 - skills - ovos_core.intent_services.ocp_service:handle_play_intent:573 - DEBUG - Playing 13 results for: wutang from spotify
Jul 30 13:43:19 mark2 ovos-core[8514]: 2024-07-30 13:43:19.786 - skills - ovos_core.intent_services.ocp_service:select_best:1003 - INFO - OVOSCommonPlay selected: ovos.common_play - 0
Jul 30 13:43:19 mark2 ovos-core[8514]: 2024-07-30 13:43:19.788 - skills - ovos_core.intent_services.ocp_service:select_best:1004 - DEBUG - Playlist(title='', artist='', position=0, image='', match_confidence=0, skill_id='ovos.common_play', skill_icon='', playback=<PlaybackType.UNDEFINED: 100>, media_type=<MediaType.GENERIC: 0>)
Jul 30 13:43:19 mark2 ovos-core[8514]: 2024-07-30 13:43:19.799 - skills - ovos_core.intent_services.ocp_service:handle_play_intent:580 - DEBUG - OCP Best match: Playlist(title='', artist='', position=0, image='', match_confidence=0, skill_id='ovos.common_play', skill_icon='', playback=<PlaybackType.UNDEFINED: 100>, media_type=<MediaType.GENERIC: 0>)
Jul 30 13:43:20 mark2 ovos-core[8514]: 2024-07-30 13:43:20.265 - skills - ovos_bus_client.util.scheduler:check_state:186 - DEBUG - Call scheduled event: skill-ovos-homescreen.openvoiceos:skill-ovos-homescreen.openvoiceosupdate_dt
Jul 30 13:43:22 mark2 ovos-core[8514]: 2024-07-30 13:43:22.118 - skills - ovos_skill_spotify.spotify:query_song:248 - DEBUG - [(0.6051282051282051, 'Wutangforever', 'Donny Goines'), (0.5666666666666667, 'Wutang', 'Blvck Plvnet'), (0.5466666666666666, 'Wutang Love from the Boys', 'Dr Suess Johnny')]
```
